### ISSUE TITLE
recipes not working

### ISSUE THREAD

**Issue by teh-herper15** [RebelKeithy/Metallurgy3#31] opened 2013-03-29 14:59 UTC
Currently, as of 3.0.0.0.7.1, the recipe for gunpowder, fertilizer, and matches do not work.

**Comment by Vyrebird** [comment] 2013-03-29 17:09
This feels reminiscent of some of the alloy recipe issues.  For example, CraftGuide sees 4 recipes for fertilizer (any two of saltpeter, potash, and magnesium, along with all three), whereas NEI sees only the all-3 recipe, and none of the recipes actually work.

For the match, CraftGuide just sees a stick in the lower-lefthand corner; I believe that implies the other ingredient(s) are invalid/nonexistent, ala a typo or a parsing error.

Gunpowder is just sulfur and saltpeter (in both), but doesn't work.

Part of the problem is inconsistent spelling of "Phosphorus" - the recipes spell it correctly (in MetallurgyMetals.java), but spreadsheet.csv and items.csv spell it "Phosphorous" (note the extra 'o' at the end).  That covers the Match and three of the fertilizers, but not the last fertilizer recipe, or the gunpowder ....
(Edit - "Phosphorus" is the noun, and "Phosphorous" one of the adjective forms for chemical compounds, as I understand it)

(and minor side note, on the topic of recipes - the Steel Metal Furnace currently requires a Bronze furnace in its recipe, but it should require a Iron furnace instead)

**Comment by Wolverine903** [comment] 2013-04-02 03:41
I noticed too that HE TNT cannot be made with recipe posted on the Metallurgy forum post.

**Comment by Vyrebird** [comment] 2013-04-02 22:44
Good point - NEI doesn't see recipes for HE or LE TNT, and craftguide doesn't see either at all.  After a cursory search, I don't see anyplace in the code that's trying to create those two recipes, so most likely they just need to be added (rather than fixed).
4x Magnesium + 4x Phosphorus + TNT (center) = LE TNT
4x Sulfur + 4x Saltpeter + TNT (center) = HE TNT

**Comment by RebelKeithy** [comment] 2013-04-04 15:45
Fixed in next update

**Closed as completed by RebelKeithy** 2013-04-04 15:45 UTC
