### ISSUE TITLE
Multiplayer minecraft crash on startup #2

### ISSUE THREAD

**Issue by Huminax** [RebelKeithy/Metallurgy3#24] opened 2013-03-26 22:26 UTC
Minecraft forge version: 1.5.1-7.7.0.608
Metallurgy version: 3.0.0.0.6.1

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 3/26/13 6:23 PM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: rebelkeithy/mods/metallurgy/metals/EntityFantasyOreFX
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:142)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:690)
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:93)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:357)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:140)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
Caused by: java.lang.NoClassDefFoundError: rebelkeithy/mods/metallurgy/metals/EntityFantasyOreFX
    at rebelkeithy.mods.metallurgy.metals.MetallurgyMetals.Init(MetallurgyMetals.java:158)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:515)
    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:165)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:98)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:689)
    ... 5 more
Caused by: java.lang.ClassNotFoundException: rebelkeithy.mods.metallurgy.metals.EntityFantasyOreFX
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:211)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 31 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/particle/EntityFX
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:200)
    ... 33 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.EntityFX
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:211)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 37 more
Caused by: java.lang.NullPointerException
    at cpw.mods.fml.relauncher.RelaunchClassLoader.findClass(RelaunchClassLoader.java:200)
    ... 39 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.5.1
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_17, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 4026185640 bytes (3839 MB) / 4116054016 bytes (3925 MB) up to 4116054016 bytes (3925 MB)
    JVM Flags: 2 total; -Xmx4096M -Xms4096M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v7.44 FML v5.1.8.608 Minecraft Forge 7.7.0.608 8 mods loaded, 8 mods active
    mcp [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized->Initialized
    Forge [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized->Initialized
    Ideas [Ideas](Metallurgy 3.0.0.0.6.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Metallurgy3Core [Metallurgy 3 Core](Metallurgy 3.0.0.0.6.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Metallurgy3Base [Metallurgy 3 Base](Metallurgy 3.0.0.0.6.1.jar) Unloaded->Constructed->Pre-initialized->Errored
    Metallurgy3Machines [Metallurgy 3 Machines](Metallurgy 3.0.0.0.6.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Metallurgy3Vanilla [Metallurgy 3 Vanilla](Metallurgy 3.0.0.0.6.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml'
    Type: Dedicated Server (map_server.txt)

**Comment by Vyrebird** [comment] 2013-03-26 23:59
Looks like the same crash as https://github.com/RebelKeithy/Metallurgy3/issues/22

**Comment by RebelKeithy** [comment] 2013-03-27 02:41
Duplicate of #22

**Closed as completed by RebelKeithy** 2013-03-27 02:41 UTC
