### ISSUE TITLE
Metallurgy armor with vanilla textures

### ISSUE THREAD

**Issue by rufus170** [RebelKeithy/Metallurgy3#15] opened 2013-03-25 20:04 UTC
Like in topic, all chestplates are chainmal, helmets are white leather caps, pants are iron and boots are diamond

**Comment by RebelKeithy** [comment] 2013-03-26 00:06
Duplicate of #14

**Closed as completed by RebelKeithy** 2013-03-26 00:06 UTC

**Comment by RebelKeithy** [comment] 2013-03-26 00:08
A better way to do this would be to change the code where the armor texture file is set. That way if you really do have armor files with uppercase letters, it wont prevent you from using them.

**Comment by Vyrebird** [comment] 2013-03-26 02:53
Yeah, your fix placement does make better sense.
(and after getting some sleep, the space-stripping loop I used is rather embarassing >< )
