### ISSUE TITLE
Stone pickaxes cannot mine tier 2 metals/ores

### ISSUE THREAD

**Issue by teh-herper15** [RebelKeithy/Metallurgy3#9] opened 2013-03-24 10:10 UTC
In metallurgy 2, I used to be able to mine metals or ores such as deep iron, sulfur, copper, or tin, but now in metallurgy 3, I can't and must use a iron pickaxe or better. Is this a deliberate design change?

**Comment by RebelKeithy** [comment] 2013-03-24 15:17
No, that's not indended, I'll look into it.

**Comment by Vyrebird** [comment] 2013-03-24 23:46
The problem is in spreadsheet.csv - the block level for those is set to '2' (ie iron-or-better), and even _iron ore_ itself is set to '2' (which thankfully M3 doesn't actually try to apply).  They should be set to '1' (stone-or-better).
(tested to be sure, and the change in spreadsheet.csv does correctly propagate to new configs, and the config setting is respected)

**Comment by RebelKeithy** [comment] 2013-03-25 00:42
ah, I was assuming 1 was wooden, and 0 was by hand. The old metallurgy spreadsheet had it listed as 1 higher also, I must have just changed it in the code

**Comment by RebelKeithy** [comment] 2013-03-26 05:29
Fixed in next release

**Closed as completed by RebelKeithy** 2013-03-26 05:29 UTC
