### ISSUE TITLE
Armor/Smelter

### ISSUE THREAD

**Issue by teh-herper15** [RebelKeithy/Metallurgy3#12] opened 2013-03-24 14:40 UTC
The armor in metallurgy 3 does not render correctly. It appears as Iron helmet, Chainmail chest plate, iron leggings, and diamond boots. Also, the smelter is missing textures when held in hand and particle textures when broken, but it is not missing its "world" texture.

**Comment by RebelKeithy** [comment] 2013-03-24 15:14
Well, that armor rendering bug is odd. I don't have the problem with the smelter missing texture while held, do you happen to be using TMI?

**Comment by DragonChef** [comment] 2013-03-24 16:06
I get that error too 

I am using MC 1.5, forge 605, metalurgy 3.0.0.0.5 and optifine A8 1.5.1

**Comment by Mem4mc** [comment] 2013-03-24 21:04
Tested with:
MultiMC 4.3.0
forge 7.7.0.603
M3-5

Output from MultiMC:
2013-03-24 15:11:48 [WARNING] [Minecraft-Client] TextureManager.createTexture called for file textures/blocks/Crusher.png, but that file does not exist. Ignoring.
2013-03-24 15:11:49 [WARNING] [Minecraft-Client] TextureManager.createTexture called for file textures/blocks/M3Mint.png, but that file does not exist. Ignoring.
2013-03-24 15:11:49 [WARNING] [Minecraft-Client] TextureManager.createTexture called for file textures/blocks/M3Lantern.png, but that file does not exist. Ignoring.
2013-03-24 15:11:50 [WARNING] [Minecraft-Client] TextureManager.createTexture called for file textures/blocks/M3PreciousChest.png, but that file does not exist. Ignoring.
2013-03-24 15:11:50 [WARNING] [Minecraft-Client] TextureManager.createTexture called for file mods/Metallurgy/textures/blocks/OreNode.png, but that file does not exist. Ignoring.

stone crusher showed texture in inventory, world and floating block. Breaking particles have no texture.
Got a set of copper armor. Same results as teh-herper15

Added  Optifine 1.5.1 HD U A8
Output from MultiMC: Same as above
stone crusher no inventory texture. Placed texture ok. break particles and floating box, no textures.
Got a set of copper armor. Same results as above

add TMI 2013 3 23 1.5.1 without optifine
Output from MultiMC: Same as above
stone crusher showed texture in inventory, world and floating block. Breaking particles have no texture.
TMI showed textures for all blocks in its display.
Got a set of copper armor. Same results as above

**Comment by Vyrebird** [comment] 2013-03-24 23:57
The armor looks the same to me - Iron Helmet, Chainmail breastplate, Iron Leggings, Diamond boots.  (this specific test was M3.0.0.0.4 with Forge600 and nothing else, but it's looked that way to me whenever I've tried M3 armor)

The particle effect when breaking a Crusher is missing for me (rather, the particles are textured with "Missing Texture"), but they are present for the smelters, furnaces, and abstractors.  (tested all crushers, all smelters, all furnaces, 1 abstractor).
(they all look fine when held)

**Comment by teh-herper15** [comment] 2013-03-25 00:54
I am only using Optifine (1.5.1 HD U A8), Backpack mod (v.1.7.8) and Forge Universal (1.5.1-7.7.0.602)

**Comment by teh-herper15** [comment] 2013-03-25 00:57
And I actually meant to say crusher, not smelter. My bad.

**Comment by RebelKeithy** [comment] 2013-03-25 01:12
It seems optifine has problems with many mods right now, the crusher texture problem is a bug with it. The particles on breaking is on our end, caused by the missing image, and the armor textures have bee fixed as of the latest commit.

**Comment by Vyrebird** [comment] 2013-03-25 02:22
The armor texture problem was _mostly_ fixed.  The code generates texture filenames with capital first letters (i.e. "Adamantine_1.png") whereas the supplied textures use lowercase filenames (i.e. "adamantine_1.png"), triggering a FileNotFoundException when it tries to access the armor textures.
(tested with renaming the textures to match what the code expected, ie renaming the file to "Adamantine_1.png", and then it worked; alternatively, also tested changing line 19 in ItemMetallurgyArmor.java to

> textureFile = texture.toLowerCase();

and that also worked.)

**Comment by RebelKeithy** [comment] 2013-03-26 05:30
Note to self: fix breaking particles for custom renderers before closing

**Comment by RebelKeithy** [comment] 2013-04-04 16:02
fixed crusher particles, finally

**Closed as completed by RebelKeithy** 2013-04-04 16:02 UTC
